# Generated by Django 4.1.2 on 2022-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Rubrics',
        ),
    ]
